title: Arabic Essentials
description: Arabic word converter
template:
  repo: arabic-essentials-template
  name: arabic-essentials
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: assignRegistrant
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
